version: '3'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
<<<<<<< HEAD
      - "8085:80"  # Access WordPress on localhost:8080
=======
      - "8085:80"  
>>>>>>> 6e4d6f5d99c38326297903ff7661f271ae3587cf
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: kzr
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: kzr
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:

